server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}

mybatis:
  #mapper 配置文件
  mapper-locations: classpath:com/myb/mapper/*.xml
  type-aliases-package: com.myb.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      myb:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置 jwt 签名加密时使用的秘钥（至少32个字符）
    admin-secret-key: itcast1234567890itcast1234567890itcast
    # 设置 jwt 过期时间
    admin-ttl: 3153600000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    # 禁用 SpringDoc 自带的默认 UI 路径，如果你只想用 Knife4j
    # enabled: false
    path: /swagger-ui.html
  # 开启 Knife4j 增强功能
  knife4j:
    enable: true
